config/routes.rb
Proyecto::Application.routes.draw do
  
  root :to => "articles#index"

  resources :articles do
    resources :comments
  end
  resources :users
  get '/admin/menu' => 'admin#menu'
  get '/admin/filtrar' => 'admin#filtrar'
 
  get '/admin/search_title' => 'admin#search_title'
  get '/admin/search_word' => 'admin#search_word'
  get '/admin/search_date' => 'admin#search_date'
  get '/admin/search_doble_date' => 'admin#search_doble_date'

  post '/articles/like' => 'articles#like' 
  post '/articles/dislike' => 'articles#dislike' 
#  get '/articles/administrador' => 'articles#administrador' 

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :presence => true
  validates :body, :presence => true
 
  belongs_to :user
  has_many :comments
  has_one :history_post
  def long_title
	"#{title} - #{published_at}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

app/models/history_post.rb
class HistoryPost < ActiveRecord::Base
	belongs_to :article
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_confirmation_of :password
	has_one :profile
	has_many :articles, -> { order('published_at DESC') },
			 :dependent => :nullify
	has_many :replies, :through => :articles, :source => :comments 
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def filtrar
		@categoria = params[:category]
		@articles = Article.where(:category => @categoria)
	end
	def menu
		@articles = Article.all.order("published_at DESC") 	
	end
	def search_title
		@titulo = params[:title]
		@articles = Article.where(:title => @titulo)
	end
	def search_word
		@palabra = params[:word]
		@articles = Article.where("body LIKE '%#{@palabra}%' ")
	end

	def search_date
		@fecha = params[:date]
		@articles = Article.where("created_at > '#{@fecha}' ")
		#@articles = Article.where("created_at > '2014-04-05' AND created_at < '2014-04-10'")
	end

	def search_doble_date
		@fecha_ini = params[:date_ini]
		@fecha_fin = params[:date_fin]
		@articles = Article.where("created_at > '#{@fecha_ini}' AND created_at < '#{@fecha_fin}'")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  


  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def dislike
      @article = Article.find(params[:id])
      var = @article.like
      var = var>0 ? var - 1 : 0
      @article.update_attributes(:like => var)
      redirect_to :action => 'index'      
  end

  def like
      @article = Article.find(params[:id])
      var = @article.like
      var = var +1
      @article.update_attributes(:like => var)
      redirect_to :action => 'index'      
  end
  def index
		@articles = Article.all 
	end

	def new
		@article = Article.new
	end
  	def show
  		@article = Article.find(params[:id])
  	end
  	def edit
  		@article = Article.find(params[:id])	
  	end

  	def update
  		@article =Article.find(params[:id])		
  		if @article.update_attributes(article_params)
    		redirect_to :action => 'show', :id => @article.id
  		else
    		render 'edit'
  		end
  	end

  	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy
  		redirect_to :action => 'index'  		
  	end
#  un  nuevo objeto Article es creado y guardado. Si la operacion de guardar es un exito, el usuario es  redirigido a la 
#  pagina show, para mostrar los detalles del nuevo articulo. Si la operacion falla el  usuario es devuelto a la  pagina
#  anterior.
#  Los parametros pasados a este metodo indican a donde se debe redirigir el navegador. En el primer  uso de redirect_to
#  el   navegador  se  redirige a la  accion   especificada(show),  y  el  parametro  :id pasado  al  metodo redirect_to,  
#  tambien transmite a la accion show  	
	def create
		@article = Article.new(article_params)
		@article.like = 0
    @article.count_word = @article.body.split.size

    if @article.save 

			redirect_to :action => 'show', :id => @article.id
		else
			redirect_to :action=> :new
		end  
	end

	def article_params
      params.require(:article).permit(:title, :category, :body,:published_at)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    	@article = Article.find(params[:article_id])
    	@comment = @article.comments.create(comment_params)
   	 	redirect_to article_path(@article)
	end

	def destroy
    	@article = Article.find(params[:article_id])
    	@comment = @article.comments.find(params[:id])
    	@comment.destroy
    	redirect_to article_path(@article)
  	end


	private
	def load_article
		@article = Article.find(params[:article_id])
	end
	def comment_params
		params.require(:comment).permit(:name, :email, :body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def new
		@user = User.new
	end	
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to articles_path, notice: 'Usuario añadido.'
		else
			render action: :new
		end
	end
	def edit
	end
	def update
		if @user.update(user_params)
			redirect_to articles_path, notice: 'Informacion actualizada.'
		else
			render action: 'edit'
		end
	end
	private
	def set_user
		@user = User.find(params[:id])
	end
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/filtrar.html.erb
<h1>LISTA DE ARTICULOS DE UNA DETERMINADA FECHA</h1>
<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Categoria</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>  <!--columnas-->
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/menu.html.erb
<h1>Estoy en menu de admin</h1>

<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Titulo</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
      <th></th>
      <th> </th>
      <th>Numero de comentarios</th>
      <th>Numero de likes</th>
      <th>Numero de palabras </th>
      <th>Categoria </th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, {:controller => 'articles', :action => 'show', :id => article.id} %></td>  <!--columnas-->
        
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
        <td><%= link_to 'Editar', {:controller => 'articles',:action => 'edit', :id => article.id} %></td>
		<td><%= link_to 'Eliminar', {:controller => 'articles',:action => :destroy, :id => article.id}, 
									 :method => :delete, :data => { :confirm => 'Seguro?' } %></td>
        <td><%= pluralize(article.comments.size, 'comentarios') %></td>  
        <td><%= article.like %></td>  
        <td><%= article.count_word %></td> 
        <td><%= article.category %></td> 
        <tr>
            <td><%= button_to 'Me gusta', {:controller => 'articles',:action => 'like', :id => article.id} %></td>
            <td><%= button_to 'No me gusta', {:controller => 'articles',:action => 'dislike', :id => article.id} %></td>  
        </tr>        
      </tr>
    <% end %>
  </tbody>
</table>
<!--
<form action="/admin/search_title" method="get">
  Buscar por titulo:
  <input type="text" name="title" value="" />
  <br/>
  <input type="submit" value="Buscar" />
</form>


<form action="/admin/search_word" method="get">
  Buscar por palabra:
  <input type="text" name="word" value="" />
  <br/>
  <input type="submit" value="Buscar" />
</form>


<form action="/admin/search_date" method="get">
  Buscar por fecha:
  <input type="text" name="date" value="" />
  <br/>
  <input type="submit" value="Buscar" />
</form>


<form action="/admin/search_doble_date" method="get">
  Buscar desde:
  <input type="text" name="date_ini" value="" />
  <br/>
  Buscar hasta:
  <input type="text" name="date_fin" value="" />
  <br/>
  <input type="submit" value="Buscar" />
</form>
-->

<form action="/admin/filtrar" method="get">
  Articulos de la categoria:
  <input type="text" name="category" value="" />
  <br/>
  <input type="submit" value="Buscar" />
</form>

app/views/admin/search_date.html.erb
<h1>LISTA DE ARTICULOS DE UNA DETERMINADA FECHA</h1>
<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Titulo</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>  <!--columnas-->
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/search_doble_date.html.erb
<h1>LISTA DE ARTICULOS</h1>
<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Titulo</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>  <!--columnas-->
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/search_title.html.erb
<h1>LISTA DE ARTICULOS</h1>
<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Titulo</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>  <!--columnas-->
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/search_word.html.erb
<h1>LISTA DE COINCIDENCIAS</h1>
<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Titulo</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>  <!--columnas-->
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> Es prohibido guardar este articulo:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :title %>
  </div>
  

  <div class="field">
    <%= f.label "Categoria" %><br />
    <%= f.text_field :category %>
  </div>
 
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :Fecha_de_publicacion %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editando articulo</h1>

<%= render 'form' %>

<%= link_to 'Pagina principal', {controller: 'articles', action: 'index'} %>

app/views/articles/index.html.erb
<h1>LISTA DE ARTICULOS</h1>
<table>  <!--crear una tabla -->
  <thead> <!--cabecera de la tabla -->
    <tr> <!-- para crear cada fila-->
      <th>Titulo</th>  <!--esta celda es la cabecera de otras celdas-->
      <th>Contenido</th>
      <th>Fecha de publicacion</th>
      <th></th>
      <th> </th>
      <th>Numero de comentarios</th>
      <th>Numero de likes</th>
      <th>Numero de palabras </th>
      <th>Categoria </th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, :action => 'show', :id => article.id %></td>  <!--columnas-->
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
        <td><%= link_to 'Editar', :action => 'edit', :id => article.id %></td>
		    <td><%= link_to 'Eliminar', {:action => :destroy, :id => article.id}, 
									 :method => :delete, :data => { :confirm => 'Seguro?' } %></td>
        <td><%= pluralize(article.comments.size, 'comentarios') %></td>  
        <td><%= article.like %></td>  
        <td><%= article.count_word %></td> 
        <td><%= article.category %></td> 
        <tr>
            <td><%= button_to 'Me gusta', :action => 'like', :id => article.id %></td>
            <td><%= button_to 'No me gusta', :action => 'dislike', :id => article.id %></td>  
        </tr>        
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'Pagina administrador', admin_menu_path %>



app/views/articles/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form' %>

<%= link_to 'Pagina principal', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @article.body %>
</p>

<h2>Comentarios</h2>
  <%= render @article.comments %>
<h2>Añadir comentario:</h2>
<%= render "comments/form" %>

<%= link_to 'Atras', :action => :index %>

app/views/comments/_comment.html.erb
<p>
  <strong>Nombre:</strong>
  <%= comment.name %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Eliminar Comentario', [comment.article, comment],
               :method => :delete,
               :data => { :confirm => '¿Estás seguro?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :comentario %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<h1>MI BLOG</h1>
		<div id="user_bar">
      		<%= link_to "Nuevo articulo", new_article_path %> |
      		<%= link_to "Pagina principal", root_path %>  |
          	<%= link_to "Pagina administrador", admin_menu_path %> 
        </div>
	</div>
	<div>
		<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
		<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
		<%= yield %>
	</div>
	<div id="footer">
   		Mi blog para taller de programacion
  	</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editando usuario</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<h1>Nuevo usuario</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>